#!/usr/bin/env bash

# Install dotfiles into $HOME
echo "Installing dotfiles:"
cd "$(dirname "$0")" || exit
for dotfile in .*; do
	SOURCE="$(pwd)/$dotfile"
	TARGET="$HOME/$dotfile"
	if [ -f "$SOURCE" ]; then
		ln -sfv "$SOURCE" "$TARGET"
	fi
done

# Install .config files into $HOME/.config
# Assumptions about .config:
# - .config contains only non-hidden files and dirs
# - Dirs contain non-hidden files/dirs
echo
echo "Installing .config files:"
for file_or_dir in .config/*; do
	if [ -f "$file_or_dir" ]; then
		f="$file_or_dir"
		ln -sfv "$(pwd)/$f" "$HOME/$f"
	else
		dir="$file_or_dir"
		mkdir -pv "$HOME/$dir"
		for f in "$dir"/*; do
			ln -snfv "$(pwd)/$f" "$HOME/$f"
		done
	fi
done
