#!/usr/bin/env bash

GLOBIGNORE=".:.."

# "Install" all dotfiles in dir by by creating symlinks in $HOME.
#
# If no argument is provided, current directory is used.
# Attempts to add into existing directories.
function install_dotfiles_in_dir {
	PATH_PREFIX=""
	if [ $# -eq 1 ]; then
		PATH_PREFIX="$1/"
	fi

	for file_or_dir in "$PATH_PREFIX"*; do
		if [ -f "$file_or_dir" ]; then
			f="$file_or_dir"
			ln -snfv "$(pwd)/$f" "$HOME/$f"
		elif [ -d "$file_or_dir" ]; then
			dir="$file_or_dir"
			mkdir -pv "$HOME/$dir"
			install_dotfiles_in_dir "$file_or_dir"
		fi
	done
}

echo "Installing dotfiles:"

# Install all dotfiles in "home" directory.
cd "$(dirname "$0")/home" || exit

install_dotfiles_in_dir
