#!/usr/bin/env bash

# Install dotfiles into $HOME
echo "Installing dotfiles:"
cd "$(dirname "$0")" || exit
for dotfile in .*; do
	SOURCE="$(pwd)/$dotfile"
	TARGET="$HOME/$dotfile"
	if [ -f "$SOURCE" ]; then
		ln -sfv "$SOURCE" "$TARGET"
	fi
done

# Install .config files into $HOME/.config
# Assumptions about .config:
# - .config contains only non-hidden dirs
# - Non-hidden dirs only contain non-hidden files/dirs
echo
echo "Installing .config files:"
for dir in .config/*; do
	mkdir -pv "$HOME/$dir"
	for f in "$dir"/*; do
		SOURCE="$(pwd)/$f"
		TARGET="$HOME/$f"
		if [ -f "$f" ]; then
			ln -sfv "$SOURCE" "$TARGET"
		else
			ln -sFv "$SOURCE" "$TARGET"
		fi
	done
done
