#!/usr/bin/env bash

# TODO: Do something other than this -- maybe just drop it?
GLOBIGNORE=".:..:.git"
shopt -u dotglob

# Install dotfiles in $HOME
cd "$(dirname "$0")" || exit
for f in .*; do
	TARGET="$HOME/$f"
	if [ -f "$TARGET" ]; then
		ln -sfv "$(pwd)/$f" "$TARGET"
	fi
done
