#!/usr/bin/env bash

GLOBIGNORE=".:..:.git"
shopt -u dotglob

# Install oh-my-zsh syntax highlighting
if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

case "$(uname -s)" in
  Darwin)
    VS_CODE_SETTINGS_PATH="$HOME/Library/Application Support/Code/User"
    FIREFOX_PROFILES_PATH="$HOME/Library/Application Support/Firefox/Profiles"
    ;;
  Linux)
    VS_CODE_SETTINGS_PATH="$HOME/.config/Code/User"
    FIREFOX_PROFILES_PATH="$HOME/.mozilla/firefox"
    ;;
esac

# Install dotfiles
cd $(dirname "$0")
for f in .*; do
  TARGET="$HOME/$f"
  if [ -d "$TARGET" ] && [ -L "$TARGET" ]; then
    rm "$TARGET"
  fi
  ln -sfv "$(pwd)/$f" "$TARGET"
done

# Install Vim plugins
vim -E +'PlugInstall' +qa > /dev/null && echo "vim-plug: Installed Vim plugins"

# Install VS Code settings (if installed)
if [ -d "$VS_CODE_SETTINGS_PATH" ]; then
  cd vscode
  for f in *.json; do
    if [ -f "$f" ]; then
      ln -sfv "$(pwd)/$f" "$VS_CODE_SETTINGS_PATH/$f"
    fi
  done
  cd "$OLDPWD"
fi

# Install Firefox UI customizations (if installed)
if [ -d "$FIREFOX_PROFILES_PATH" ]; then
  cd firefox
  for profile_dir in "$FIREFOX_PROFILES_PATH"/*.default*; do
    for f in *; do
      TARGET="$profile_dir/$f"
      if [ -d "$TARGET" ] && [ -L "$TARGET" ]; then
        rm "$TARGET"
      fi
      ln -sfv "$(pwd)/$f" "$TARGET"
    done
  done
  cd "$OLDPWD"
fi
