#!/usr/bin/env bash

backup() {
  if [ -e "$1" ]; then
    echo "- Back up $1 -> $1.bak"
    mv "$1" "$1.bak"
  fi
}

symlink() {
  echo "- Symlink $2 -> $1"
  ln -s "$1" "$2"
}

# "Install" dotfiles that have not already been installed
for f in .*; do
  if [ -f "$f" ]; then
    if [ "$(readlink $HOME/$f)" != "$(pwd)/$f" ]; then
      backup "$HOME/$f"
      symlink "$(pwd)/$f" "$HOME/$f"
    fi
  fi
done

# zsh: oh-my-zsh
backup "$HOME/.oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# vim: Vundle
backup "$HOME/.vim"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall! +qall
