#!/usr/bin/env bash

GLOBIGNORE=".:..:.git"
shopt -u dotglob

# Install oh-my-zsh syntax highlighting
if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

# Install dotfiles
cd $(dirname "$0")
for f in .*; do
  if [ -L "$HOME/$f" ]; then
    rm "$HOME/$f"
  fi
  ln -sfv "$(pwd)/$f" "$HOME/$f"
done

# Install VS Code settings (if VS Code is installed)
VS_CODE_SETTINGS_PATH=""
case "$(uname -s)" in
  Darwin)
    VS_CODE_SETTINGS_PATH="$HOME/Library/Application Support/Code/User"
    ;;
  Linux)
    VS_CODE_SETTINGS_PATH="$HOME/.config/Code/User"
    ;;
esac
if [ -d "$VS_CODE_SETTINGS_PATH" ]; then
  cd vscode
  for f in *.json; do
    if [ -f "$f" ]; then
      ln -sfv "$(pwd)/$f" "$VS_CODE_SETTINGS_PATH/$f"
    fi
  done
  cd "$OLDPWD"
fi
