#!/usr/bin/env bash

symlink_with_backup() {
  if [ -e "$2" ]; then
    echo "    - Backing up $2 as $2.bak"
    mv "$2" "$2.bak"
  fi
  echo "    - Creating symlink $2 -> $1"
  ln -s "$1" "$2"
}

# "Install" dotfiles only if it has not already been installed
for f in .*; do
  if [ -f "$f" ]; then
    if [ "$(readlink $HOME/$f)" != "$(pwd)/$f" ]; then
      echo "- Installing $f"
      symlink_with_backup "$(pwd)/$f" "$HOME/$f"
    else
      echo "- Skipping $f"
    fi
  fi
done

# zsh: oh-my-zsh
# sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# vim: Vundle
# git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
# vim +PluginInstall! +qall
