#!/usr/bin/env bash

rm "$HOME/.zshrc"
rm "$HOME/.zsh_aliases"
rm "$HOME/.hushlogin"
rm -rf "$HOME/.oh-my-zsh"
brew uninstall zsh zsh-completions
# chsh -s /bin/bash # TODO: Change to /bin/zsh after MacOS 10.15 is released

rm "$HOME/.gitconfig"
rm "$HOME/.gitignore_global"

rm "$HOME/.vimrc"
rm -rf "$HOME/.vim/bundle/Vundle.vim"
