#!/usr/bin/env bash

rm_symlink_and_restore() {
  if [ -L "$1" ]; then
    echo "    - Remove symlink $1"
    rm "$1"
    
    if [ -f "$1.bak" ]; then
      echo "    - Restore $1 from $1.bak"
      mv "$1.bak" "$1"
    fi
  fi
}

# "Uninstall" dotfiles that are symlinks pointing at files in this directory
for f in .*; do
  if [ -f "$f" ]; then
    if [ -L "$HOME/$f" ]; then
      if [ "$(readlink $HOME/$f)" = "$(pwd)/$f" ]; then
        echo "- Uninstall $f"
        rm_symlink_and_restore "$HOME/$f"
      fi
    fi
  fi
done

# TODO: Uncomment
# TODO: Fail silently (e.g., if it isn't there -- or maybe only remove if it is there, otherwise don't fail silently
# rm -rf ".oh-my-zsh"
# rm -rf ".vim/bundle/Vundle.vim"
