#!/usr/bin/env bash

rm_and_restore() {
  if [ -e $1 ]; then
    echo "- Remove $1"
    rm -rf "$1"
  fi

  if [ -f "$1.bak" ]; then
    echo "- Restore $1 <- $1.bak"
    mv "$1.bak" "$1"
  fi
}

# "Uninstall" dotfiles that are symlinks pointing at files in this directory
for f in .*; do
  if [ -f "$f" ]; then
    if [ -L "$HOME/$f" ]; then
      if [ "$(readlink $HOME/$f)" = "$(pwd)/$f" ]; then
        rm_and_restore "$HOME/$f"
      fi
    fi
  fi
done

# Remove oh-my-zsh, Vundle
rm_and_restore "$HOME/.oh-my-zsh"
rm_and_restore "$HOME/.vim"
