format = """
$username\
$hostname\
$directory\
$jobs\
$status\
$character"""

right_format = """"""

add_newline = false

[username]
style_root = "red"
style_user = "243"
format = "[$user]($style)[@](243)"

[hostname]
style = "243"
format = "[$hostname:]($style)"

[directory]
truncation_length = 20
truncate_to_repo = false
truncation_symbol = "…/"
read_only = ""
style = "bold blue"

[jobs]
style = "bold 13"
symbol = "&"

[status]
format = "[$status ]($style)"
disabled = false

[character]
success_symbol = "[\\$](grey)"
error_symbol = "[\\$](bold red)"
