theme = "ayu_dark"

[editor]
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
0 = "goto_first_nonwhitespace"
"$" = "goto_line_end"
V = ["extend_to_line_bounds", "select_mode"]
L = ["select_mode", "goto_line_end"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
L = ["goto_line_end"]
j = ["extend_line_down", "extend_to_line_bounds"]
k = ["extend_line_up", "extend_to_line_bounds"]
