theme = "ayu_dark"

[editor]
true-color = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]

# Make it easier to escape multiple selections
esc = ["collapse_selection", "keep_primary_selection"]

# Navigation
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
0 = "goto_first_nonwhitespace"
"$" = "goto_line_end"

# Selection
";" = ["select_mode", "goto_line_end"]
V = ["extend_to_line_bounds", "select_mode"]

# More intuitive forward/backward
H = "jump_backward"
L = "jump_forward"

# Easy buffer switching -- following bufferline layout
J = "goto_previous_buffer"
K = "goto_next_buffer"
C-j = "join_selections"
C-k = "keep_selections"
X = ":buffer-close"

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
";" = "goto_line_end"
j = ["extend_line_down", "extend_to_line_bounds"]
k = ["extend_line_up", "extend_to_line_bounds"]
