theme = "ayu_dark"

[editor]
true-color = true
bufferline = "never"
scroll-lines = 1

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.search]
smart-case = false

[editor.soft-wrap]
enable = true


[keys.normal]

# Escape multiple selections easily
esc = ["collapse_selection", "keep_primary_selection"]

# Selection
V = ["extend_to_line_bounds", "select_mode"]

# Navigation
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.select]

# Navigation
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]

# Make j/k work like Vim in visual block mode
j = ["extend_line_down", "extend_to_line_bounds"]
k = ["extend_line_up", "extend_to_line_bounds"]
