theme = "ayu_dark"

[editor]
true-color = true
bufferline = "never"
scroll-lines = 1
gutters = ["diagnostics", "line-numbers", "spacer"] # Disable diff by default

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.search]
smart-case = false

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # Escape multiple selections easily
X = "extend_line_above"
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"+" = "goto_prev_diag"
"=" = "goto_next_diag"

[keys.select]
X = "extend_line_above"
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]

[keys.normal.space]
f = "file_picker_in_current_directory" # Prefer opening file picker in cwd
F = "file_picker"
G = "file_picker_in_current_buffer_directory"

[keys.normal.g]
w = "rotate_view"
