theme = "ayu_dark"

[editor]
true-color = true
bufferline = "never"
scroll-lines = 1

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.search]
smart-case = false

[editor.soft-wrap]
enable = true

[keys.normal]

# Make it easier to escape multiple selections
esc = ["collapse_selection", "keep_primary_selection"]

# Navigation
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
0 = "goto_first_nonwhitespace"
"$" = "goto_line_end"

# Selection
";" = ["select_mode", "goto_line_end"]
V = ["extend_to_line_bounds", "select_mode"]

[keys.select]

# Navigation
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"

# Selection
";" = "goto_line_end"

# Make j/k work like Vim in visual block mode
j = ["extend_line_down", "extend_to_line_bounds"]
k = ["extend_line_up", "extend_to_line_bounds"]
