theme = "ayu_dark"

[editor]
true-color = true
bufferline = "never"
scroll-lines = 1
gutters = ["diagnostics", "line-numbers", "spacer"] # Disable diff by default

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.search]
smart-case = false

[editor.soft-wrap]
enable = true

[keys.normal]

# Escape multiple selections easily
esc = ["collapse_selection", "keep_primary_selection"]

X = "extend_line_above"

# Navigate via paragraphs easier
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.select]

X = "extend_line_above"

# Navigate via paragraphs easier
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
