name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Node (for installing Prettier)
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install shfmt
        run: sudo snap install shfmt
      - name: Install Prettier
        run: npm install --location=global prettier
      - name: Install shellcheck
        run: sudo apt install shellcheck
      - name: Check format
        run: make check-format
      - name: Lint
        run: make lint
      - name: Test install
        run: install
      - name: Test update
        run: update
